---
title: "Cholera outbreak model"
output: github_document
date: "2023-02-27"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, eval = FALSE, warning = F)
```

## Load the package

```{r cars}
devtools::load_all()
```

## Run the model
```{r}
devtools::load_all()
init <- initialize_params()

print_params <- function(params){
  n <- names(params)
  for(i in seq_along(n)){
    cat(paste0(n[i], "=", params[n[i]]), ", ")
  }
}
print_params(init)
```

```{r}
PARAMETERS <- initialize_params()
# PARAMETERS$model <- seiarw
pop <- 1e5
pop_scale <- 0.07
prop_init_R <- 0.6
prop_init_I <- 0.001 
PARAMETERS$init$R <- prop_init_R * pop * pop_scale
PARAMETERS$init$I <- prop_init_I * pop * pop_scale
PARAMETERS$init$S <- pop * pop_scale - PARAMETERS$init$I - PARAMETERS$init$I


plot(1:nrow(d), d$CI, type="l")


# ?data.table::frollsum
df <- data.frame(matrix(NA, nrow=52, ncol=10))
df$week=1:52
for(i in 1:10){
  parm <- c(R0=2, R0W=1, case_threshold=10, alpha=(i-1)/10)
  d <- daily_incidence(pars=parm)
  weekroll <- data.table::frollsum(d$CI, n=7)
  sq <- seq(7, length(weekroll), by=7)
  df[, i] <- weekroll[sq]
}

head(df, n=20)
names(df) <- c(paste0(seq(0,90,10)," %"), "Week")
df <- df[,c(seq(1,9,2),11)]
library(tidyr)
# dflong <- pivot_longer(df, cols=1:ncol(df), names_to = "Reduction")
dflong <- pivot_longer(df, cols=(!Week), names_to = "Reduction")
library(ggplot2)
mycolors <- c("dodgerblue2", "#E31A1C", "green4", "#6A3D9A", "#FF7F00",
                "black", "gold1", "skyblue2", "palegreen2", "#FDBF6F",
                "gray70", "maroon", "orchid1", "darkturquoise",
                "darkorange4", "brown")

p <- ggplot(dflong) +
  geom_line(aes(Week, value, color=Reduction), linewidth=1)+
  labs(x="Week", y="Case")+
  scale_color_manual("Intervention", values=mycolors[1:10])+
  theme_classic()+
  theme(panel.grid.major = element_line(colour="grey95", linewidth=0.3),
    text = element_text(size=14), axis.text = element_text(size=14))
p

ggsave("plots/outbreak_intervention.png", p, width=3.4*2, height=2.7*2, unit="in")



# sum(d$CI)
cat("outbreak size:", round(sum(weekly)), "\n")
# df <- data.frame(week = 1:length(weekly), case = weekly)
# library(ggplot2)
# p <- ggplot(df) +
#   geom_col(aes(week, case), fill = "brown") + 
#   labs(x="Week", y="Case")+
#   theme_classic()+
#   theme(panel.grid.major = element_line(colour="grey95", linewidth=0.3),
#     text = element_text(size=14),
#         axis.text = element_text(size=14))
# p
# ggsave("plots/typical_outbreak.png", p, width=3.4*2, height=2.7*2, unit="in")

out <- PARAMETERS$model(PARAMETERS)
day_filter <- seq(1, by=round(1/PARAMETERS$tau), length.out=(PARAMETERS$ndays+1))
out <- out[day_filter, ]




```


## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

