// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// reulermultinom
NumericVector reulermultinom(double size, NumericVector rate, double dt);
RcppExport SEXP _CholeraOutbreakModel_reulermultinom(SEXP sizeSEXP, SEXP rateSEXP, SEXP dtSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type size(sizeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rate(rateSEXP);
    Rcpp::traits::input_parameter< double >::type dt(dtSEXP);
    rcpp_result_gen = Rcpp::wrap(reulermultinom(size, rate, dt));
    return rcpp_result_gen;
END_RCPP
}
// seiarw_euler
List seiarw_euler(List params);
RcppExport SEXP _CholeraOutbreakModel_seiarw_euler(SEXP paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type params(paramsSEXP);
    rcpp_result_gen = Rcpp::wrap(seiarw_euler(params));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_CholeraOutbreakModel_reulermultinom", (DL_FUNC) &_CholeraOutbreakModel_reulermultinom, 3},
    {"_CholeraOutbreakModel_seiarw_euler", (DL_FUNC) &_CholeraOutbreakModel_seiarw_euler, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_CholeraOutbreakModel(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
