// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// seiarw
List seiarw(List params);
RcppExport SEXP _CholeraOutbreakModel_seiarw(SEXP paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type params(paramsSEXP);
    rcpp_result_gen = Rcpp::wrap(seiarw(params));
    return rcpp_result_gen;
END_RCPP
}
// seiarw_2ag_erlang
List seiarw_2ag_erlang(List params);
RcppExport SEXP _CholeraOutbreakModel_seiarw_2ag_erlang(SEXP paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type params(paramsSEXP);
    rcpp_result_gen = Rcpp::wrap(seiarw_2ag_erlang(params));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_CholeraOutbreakModel_seiarw", (DL_FUNC) &_CholeraOutbreakModel_seiarw, 1},
    {"_CholeraOutbreakModel_seiarw_2ag_erlang", (DL_FUNC) &_CholeraOutbreakModel_seiarw_2ag_erlang, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_CholeraOutbreakModel(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
