# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

seiarw <- function(params) {
    .Call(`_CholeraOutbreakModel_seiarw`, params)
}

seiarw_2ag_erlang <- function(params) {
    .Call(`_CholeraOutbreakModel_seiarw_2ag_erlang`, params)
}

